import type { Metadata } from 'next'
import { notoSansKr, openSans } from '@/lib/font'
import '@/lib/css/globals.css'

export const metadata: Metadata = {
    title: 'Bread & Sauce',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='ko'>
            <body className={`${notoSansKr.variable} ${openSans.variable} antialiased`}>
                <div className='min-h-dvh w-full'>{children}</div>hello zzzz
            </body>
        </html>
    )
}
