import '@/lib/css/globals.css';
import { notoSansKr, openSans } from '@/lib/font';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Bread & Sauce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${notoSansKr.variable} ${openSans.variable} antialiased`}>
        <div className='min-h-dvh w-full'>{children}</div>hello zzzz
      </body>
    </html>
  );
}
